import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Gabrielle Ford | Full Stack Web Developer',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>{children}</body>
    </html>
  );
}
